repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.71.0
  hooks:
    - id: terraform_providers_lock
      args:
          - --args=-platform=darwin_amd64
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_tfsec
      args:
        - >
          --args=--format json
          --no-color
    - id: terraform_validate
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: check-symlinks
