---
name: Code Analysis
on:  # yamllint disable-line rule:truthy
  # Trigger the workflow on pushes to the default branch and all pull requests.
  push:
    branches:
      - main
  pull_request:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Lint markdown files
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: 'README.md CHANGELOG.md PULL_REQUEST_TEMPLATE.md .github/ docs/ profile/'
          fix: true

  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Yaml Lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: .yamllint.yml
